<a href="https://colab.research.google.com/github/sharube98/CognoRise/blob/main/DL3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Cat & Dog classification

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
from sklearn.svm import SVC
import numpy as np
import matplotlib.pyplot as plt
import os
from skimage.io import imread
from sklearn.model_selection import train_test_split
from skimage.transform import resize

In [3]:
os.listdir('/content/drive/MyDrive/Data')

['Cat', 'Dog']

In [4]:
len(os.listdir("/content/drive/MyDrive/Data/Cat"))

85

In [5]:
len(os.listdir("/content/drive/MyDrive/Data/Dog"))

68

In [6]:
cat=os.path.join("/content/drive/MyDrive/Data","Cat")
for i in os.listdir(cat):
  print(i)


cat.80.jpg
cat.81.jpg
cat.84.jpg
cat.87.jpg
cat.44.jpg
cat.99.jpg
cat.71.jpg
cat.78.jpg
cat.96.jpg
cat.76.jpg
cat.70.jpg
cat.79.jpg
cat.83.jpg
cat.52.jpg
cat.64.jpg
cat.93.jpg
cat.97.jpg
cat.86.jpg
cat.69.jpg
cat.66.jpg
cat.90.jpg
cat.58.jpg
cat.94.jpg
cat.95.jpg
cat.63.jpg
cat.88.jpg
cat.60.jpg
cat.89.jpg
cat.40.jpg
cat.39.jpg
cat.85.jpg
cat.82.jpg
cat.72.jpg
cat.67.jpg
cat.68.jpg
cat.92.jpg
cat.35.jpg
cat.36.jpg
cat.41.jpg
cat.91.jpg
cat.73.jpg
cat.65.jpg
cat.75.jpg
cat.98.jpg
cat.77.jpg
cat.47.jpg
cat.117.jpg
cat.38.jpg
cat.102.jpg
cat.118.jpg
cat.49.jpg
cat.51.jpg
cat.53.jpg
cat.61.jpg
cat.54.jpg
cat.42.jpg
cat.101.jpg
cat.107.jpg
cat.116.jpg
cat.105.jpg
cat.109.jpg
cat.100.jpg
cat.119.jpg
cat.37.jpg
cat.59.jpg
cat.55.jpg
cat.106.jpg
cat.50.jpg
cat.57.jpg
cat.62.jpg
cat.56.jpg
cat.114.jpg
cat.46.jpg
cat.113.jpg
cat.110.jpg
cat.74.jpg
cat.43.jpg
cat.45.jpg
cat.48.jpg
cat.115.jpg
cat.112.jpg
cat.103.jpg
cat.104.jpg
cat.111.jpg
cat.108.jpg


In [7]:
dog="/content/drive/MyDrive/Data/Dog"
for i in os.listdir(dog):
  print(i)

dog.66.jpg
dog.7.jpg
dog.63.jpg
dog.68.jpg
dog.8.jpg
dog.9.jpg
dog.65.jpg
dog.59.jpg
dog.41.jpg
dog.60.jpg
dog.53.jpg
dog.50.jpg
dog.49.jpg
dog.36.jpg
dog.40.jpg
dog.6.jpg
dog.61.jpg
dog.4.jpg
dog.56.jpg
dog.29.jpg
dog.52.jpg
dog.43.jpg
dog.64.jpg
dog.26.jpg
dog.5.jpg
dog.67.jpg
dog.45.jpg
dog.46.jpg
dog.39.jpg
dog.58.jpg
dog.62.jpg
dog.57.jpg
dog.55.jpg
dog.42.jpg
dog.35.jpg
dog.47.jpg
dog.3.jpg
dog.38.jpg
dog.48.jpg
dog.34.jpg
dog.44.jpg
dog.51.jpg
dog.21.jpg
dog.1.jpg
dog.11.jpg
dog.15.jpg
dog.14.jpg
dog.24.jpg
dog.22.jpg
dog.30.jpg
dog.2.jpg
dog.25.jpg
dog.54.jpg
dog.13.jpg
dog.23.jpg
dog.27.jpg
dog.28.jpg
dog.20.jpg
dog.32.jpg
dog.10.jpg
dog.16.jpg
dog.33.jpg
dog.19.jpg
dog.12.jpg
dog.37.jpg
dog.18.jpg
dog.17.jpg
dog.31.jpg


In [8]:
flat_data=[] #used for collecting input data
target_data=[] #used for collecting output data
category=["Cat","Dog"]
maindir="/content/drive/MyDrive/Data"

In [9]:
for i in category:
    print("Loading categories......")
    npath=os.path.join(maindir,i)
    for im in os.listdir(npath):
      img=imread(os.path.join(npath,im))
      img_re=resize(img,(150,150,3))
      flat_data.append(img_re.flatten())
      target_data.append(category.index(i))
    print(i,"Loaded Completely")

Loading categories......
Cat Loaded Completely
Loading categories......
Dog Loaded Completely


In [10]:
flat=np.array(flat_data)
target=np.array(target_data)
df=pd.DataFrame(flat)
df

0         1         2         3         4         5         6      \
0    0.302291  0.294447  0.212094  0.305703  0.297860  0.215507  0.308719   
1    0.058648  0.058648  0.090021  0.063648  0.063648  0.095021  0.050579   
2    0.470525  0.337191  0.190404  0.544988  0.411654  0.264867  0.520875   
3    0.094118  0.094118  0.086275  0.094118  0.094118  0.086275  0.094118   
4    0.310585  0.120677  0.101069  0.307774  0.124558  0.104951  0.297252   
..        ...       ...       ...       ...       ...       ...       ...   
148  0.301846  0.556748  0.776355  0.299352  0.554254  0.773862  0.296074   
149  0.158074  0.204743  0.140362  0.211659  0.151758  0.123442  0.278121   
150  0.612096  0.506214  0.470920  0.568027  0.467242  0.437046  0.544847   
151  0.929817  0.929817  0.937660  0.935398  0.935398  0.943241  0.939880   
152  0.076956  0.131472  0.080685  0.079919  0.126656  0.079574  0.071057   

        7         8         9      ...     67490     67491     67492  \
0    0.300876  0.218523  0.308718  ...  0.527509  0.594982  0.579296   
1    0.050579  0.081951  0.030930  ...  0.154332  0.153764  0.130191   
2    0.387541  0.240753  0.511482  ...  0.222638  0.472381  0.347523   
3    0.094118  0.086275  0.094117  ...  0.413832  0.417687  0.416508   
4    0.125582  0.106907  0.277894  ...  0.366715  0.255025  0.282688   
..        ...       ...       ...  ...       ...       ...       ...   
148  0.550453  0.772675  0.300729  ...  0.070725  0.629045  0.249300   
149  0.085468  0.097992  0.313758  ...  0.360298  0.438806  0.368338   
150  0.447135  0.420694  0.409511  ...  0.361312  0.395262  0.348204   
151  0.939880  0.947724  0.939183  ...  0.896221  0.929117  0.925190   
152  0.102409  0.059763  0.082444  ...  0.295727  0.221501  0.252996   

        67493     67494     67495     67496     67497     67498     67499  
0    0.532237  0.591976  0.576290  0.529231  0.588565  0.572879  0.525820  
1    0.140375  0.141987  0.117832  0.121939  0.140351  0.106599  0.110030  
2    0.264476  0.456843  0.332844  0.250442  0.515859  0.400043  0.315856  
3    0.406373  0.387455  0.390984  0.381789  0.370306  0.371310  0.369780  
4    0.360225  0.259416  0.282780  0.357647  0.262495  0.283047  0.357647  
..        ...       ...       ...       ...       ...       ...       ...  
148  0.084594  0.632379  0.250166  0.091354  0.632379  0.249008  0.093671  
149  0.360455  0.442407  0.371939  0.364056  0.437485  0.367017  0.359134  
150  0.348204  0.372594  0.325535  0.325535  0.386530  0.339471  0.339471  
151  0.917028  0.936635  0.932713  0.917103  0.947144  0.943223  0.927537  
152  0.304165  0.222034  0.253408  0.304633  0.223267  0.254542  0.305816  

[153 rows x 67500 columns]

In [11]:
df.shape


(153, 67500)

In [12]:
df['target']=target_data
df.shape


(153, 67501)

In [17]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)


In [18]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(x_train)
x_train=sc.transform(x_train)
x_test=sc.transform(x_test)
x_train


array([[ 0.03158756,  0.43533593,  0.42686597, ..., -0.34716834,
        -0.27080823, -0.19778225],
       [-0.62687082, -0.7708458 , -1.03036122, ...,  0.60371078,
         0.63090196,  0.67073207],
       [-0.67955536, -0.8301269 , -0.84548865, ...,  1.42963889,
         1.39013901,  1.09325476],
       ...,
       [ 0.72412135,  0.3791121 ,  0.29777841, ..., -0.45555205,
        -0.5359646 , -0.44097182],
       [ 0.14723246,  0.16965362,  0.51078226, ..., -0.49449755,
        -0.49386085, -0.21286503],
       [ 0.62341642,  0.54761559,  0.49504977, ..., -1.19523459,
        -1.0546645 , -0.87725858]])

In [14]:
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array([1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0])

In [15]:
from sklearn.metrics import confusion_matrix,accuracy_score
print("Accuracy_score is",accuracy_score(y_test,y_pred))

Accuracy_score is 0.6774193548387096


Prediction:this image is cat or not

In [20]:
path1='/content/drive/MyDrive/Data/Dog/dog.1.jpg'
img=imread(path1)
img=resize(img,(150,150,3)).flatten().reshape(1,-1)
model.predict(img)

array([1])